### ISSUE TITLE
AquaStar-1.5.1-i386.AppImage redirects to flash end of life page

### ISSUE THREAD

**Issue by ghost** [aquaspy/AquaStar#19]
The AquaStar-1.5.1-i386,AppImage loads this screen:

![Screenshot-2021-12-5_1](https://user-images.githubusercontent.com/79065413/144769189-712831b5-4fcf-49e7-9ba6-8615891660b4.png)

On click, this screen redirects me to flash end of life page and the terminal shows "NOT SANDBOXED". 
I'm using Ubuntu 18.04.

Debug info:
OS - linux
ARCH ia32

**Comment by aquaspy** [comment]
Hmm thanks for reporting this. It is really weird, maybe this is some problem at electron-builder or some mess with flash 32 bits.

Can you try to run it on your computer to check if this will work?

git clone https://github.com/aquaspy/AquaStar.git

cd Aquastar

npm install

npm start electron

**Comment by aquaspy** [comment]
also, can you confirm me what is the return os 

uname -a

on a terminal?

**Comment by AugustoRavazoli** [comment]
Hello Aquaspy, i tried building as you say but i got the same screen. uname -a returns this: 

Linux lubuntu 4.15.0-163-generic #171-Ubuntu SMP Fri Nov 5 11:53:11 UTC 2021 i686 i686 i686 GNU/Linux

**Comment by CaioFViana** [comment]
I think i know what happened... our flash version for 32 bit linux might not be downgraded from the EoL stuff on january 2020. We will search for a "older" flash 32 bit version, and then, updating the repository.

**Comment by CaioFViana** [comment]
Ok, i am very sorry as college and lots of stuff came in and I 100% forgot about this. I have the new flash version in hands and the repository will update TODAY.

**Comment by aquaspy** [comment]
Hey, I just updated the new flash version. Should fix this issue :)
